services:
  app:
    build: .
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge
