services:
  app:
    build: .
    ports:
      - "80:80"
    networks:
      - backend
    environment:
      - FISTOLI_MONGO_HOST="mongodb"
      - FISTOLI_REDIS_ADDR="redis"
      - FISTOLI_MONGO_PATH="/app/storage/file_storage"
    depends_on:
      - mongodb
      - sessions

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - backend

volumes:
  mongodb_data:
  redis_data:

networks:
  backend:
    driver: bridge
