mongo:
  host: "localhost"
  port: 27017
  timeoutSeconds: 10
  dbName: "cloud"
  collectionUsers: "Users"
  path: "C:/Users/sawok/GolandProjects/cloudService/storage/file_storage"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  maxRetries: 5
  dialTimeout: 10
  timeout: 5

postgres:
  user: "server"
  password: "mysecretpassword"
  host: "postgres"
  port: "5432"
  dbName: "fistoli"
  sslMode: "disable"
  driverName: "postgres"

migrate:
  source: "./migrations"