mongo:
  host: "localhost"
  port: 27017
  timeoutSeconds: 10
  dbName: "cloud"
  collectionUsers: "Users"
  collectionFiles: "Files"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  maxRetries: 5
  dialTimeout: 10
  timeout: 5