mongo:
  host: "mongodb"
  port: 27017
  timeoutSeconds: 10
  dbName: "cloud"
  collection: "user"

redis:
  addr: "sessions:6379"
  password: ""
  db: 0
  max_retries: 5
  dial_timeout: 10
  timeout: 5